/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import functionalities.BackupManager;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Ershadi
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageIncomeButton = new javax.swing.JButton();
        manageExpenditureButton = new javax.swing.JButton();
        manageDonatorButton = new javax.swing.JButton();
        manageExpenditureReasonButton = new javax.swing.JButton();
        manageBackupButton = new javax.swing.JButton();
        manageaIncomeReasonButton = new javax.swing.JButton();
        manageResponsibleButton = new javax.swing.JButton();
        manageUserButton = new javax.swing.JButton();
        containerPanel = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        manageIncomeButton.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        manageIncomeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/income.png"))); // NOI18N
        manageIncomeButton.setText("Manage Income");
        manageIncomeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageIncomeButtonActionPerformed(evt);
            }
        });

        manageExpenditureButton.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        manageExpenditureButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/expend.png"))); // NOI18N
        manageExpenditureButton.setText("Manage Expenditure");
        manageExpenditureButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageExpenditureButtonActionPerformed(evt);
            }
        });

        manageDonatorButton.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        manageDonatorButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/donator.png"))); // NOI18N
        manageDonatorButton.setText("Manage Donator");
        manageDonatorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageDonatorButtonActionPerformed(evt);
            }
        });

        manageExpenditureReasonButton.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        manageExpenditureReasonButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/report.png"))); // NOI18N
        manageExpenditureReasonButton.setText("View Reports");
        manageExpenditureReasonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageExpenditureReasonButtonActionPerformed(evt);
            }
        });

        manageBackupButton.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        manageBackupButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/backup.png"))); // NOI18N
        manageBackupButton.setText("Manage backup");
        manageBackupButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageBackupButtonActionPerformed(evt);
            }
        });

        manageaIncomeReasonButton.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        manageaIncomeReasonButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reason.png"))); // NOI18N
        manageaIncomeReasonButton.setText("Manage Income & Expenditure Reason");
        manageaIncomeReasonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageaIncomeReasonButtonActionPerformed(evt);
            }
        });

        manageResponsibleButton.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        manageResponsibleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/responsible.png"))); // NOI18N
        manageResponsibleButton.setText("Manage Responsible");
        manageResponsibleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageResponsibleButtonActionPerformed(evt);
            }
        });

        manageUserButton.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        manageUserButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user.png"))); // NOI18N
        manageUserButton.setText("Users");
        manageUserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageUserButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(containerPanel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(manageIncomeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(manageExpenditureButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageDonatorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageResponsibleButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageaIncomeReasonButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageExpenditureReasonButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageBackupButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(manageUserButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageIncomeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(manageExpenditureReasonButton, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                        .addComponent(manageBackupButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(manageUserButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(manageaIncomeReasonButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageResponsibleButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageDonatorButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageExpenditureButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(containerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void manageIncomeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageIncomeButtonActionPerformed
        containerPanel.removeAll();
        ManageIncome manageIncome = new ManageIncome();
        containerPanel.add(manageIncome.manageIncomeTabbedPane);
    }//GEN-LAST:event_manageIncomeButtonActionPerformed

    private void manageExpenditureButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageExpenditureButtonActionPerformed
        containerPanel.removeAll();
        ManageExpenditure manageExpenditure = new ManageExpenditure();
        containerPanel.add(manageExpenditure.manageExpenditureTabbedPane);
    }//GEN-LAST:event_manageExpenditureButtonActionPerformed

    private void manageDonatorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageDonatorButtonActionPerformed
        containerPanel.removeAll();
        ManageDonator manageDonator = new ManageDonator();
        containerPanel.add(manageDonator.manageDonatorTabbedPane);
    }//GEN-LAST:event_manageDonatorButtonActionPerformed

    private void manageResponsibleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageResponsibleButtonActionPerformed
        containerPanel.removeAll();
        ManageResponsible manageResponsible = new ManageResponsible();
        containerPanel.add(manageResponsible.manageResponsiblePanel);
    }//GEN-LAST:event_manageResponsibleButtonActionPerformed

    private void manageaIncomeReasonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageaIncomeReasonButtonActionPerformed
        containerPanel.removeAll();
        ManageIncomeAndExpenditureReason manageIncomeAndExpenditureReason = new ManageIncomeAndExpenditureReason();
        containerPanel.add(manageIncomeAndExpenditureReason.manageIncomeAndExpenditureReasonTabbedPane);
    }//GEN-LAST:event_manageaIncomeReasonButtonActionPerformed

    private void manageExpenditureReasonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageExpenditureReasonButtonActionPerformed
        containerPanel.removeAll();
        ViewReports viewReports = new ViewReports();
        containerPanel.add(viewReports.reportPanel);
    }//GEN-LAST:event_manageExpenditureReasonButtonActionPerformed

    private void manageBackupButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageBackupButtonActionPerformed
        Object selectionValues[] = {"Save backup", "Restore backup"};
        Icon icon = new ImageIcon(Toolkit.getDefaultToolkit().getImage("src/img/backup.png"));
        Object result = JOptionPane.showInputDialog(rootPane, "Select your action from the below selection box.", null, 2, icon, selectionValues, rootPaneCheckingEnabled);

        boolean bool = false;
        try {
            if (result.equals("Save backup")) {
                JFileChooser saveFileChooser = new JFileChooser("db_backup");
                int returnVal = saveFileChooser.showSaveDialog(this);
                if (returnVal == JFileChooser.APPROVE_OPTION) {
                    bool = BackupManager.createBackup("iaedb", "root", "admin", saveFileChooser.getSelectedFile().getPath() + ".dump");
                    if (bool) {
                        JOptionPane.showMessageDialog(this, "Backup saved successfully.");
                    } else {
                        JOptionPane.showMessageDialog(this, "Backup failed to save.");
                    }
                }
            } else if (result.equals("Restore backup")) {
                AdminPassword adminPassword = new AdminPassword(this, rootPaneCheckingEnabled);
                adminPassword.setLocationRelativeTo(null);
                adminPassword.setVisible(true);
            }
        } catch (Exception e) {
        }

        selectionValues = null;
        icon = null;
        result = null;
        System.gc();
    }//GEN-LAST:event_manageBackupButtonActionPerformed

    private void manageUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageUserButtonActionPerformed
        containerPanel.removeAll();
        ManageUser manageUser = new ManageUser();
        containerPanel.add(manageUser.manageUserTabbedPane);
    }//GEN-LAST:event_manageUserButtonActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int result = JOptionPane.showConfirmDialog(this, "Do yo want to exit");
        if (result == 0) {
            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            Date date = new Date();
            String fileName = dateFormat.format(date);
            BackupManager.createBackup("iaedb", "root", "admin", "db_backup/" + fileName + ".dump");
            System.gc();
            System.exit(0);
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane containerPanel;
    private javax.swing.JButton manageBackupButton;
    private javax.swing.JButton manageDonatorButton;
    private javax.swing.JButton manageExpenditureButton;
    private javax.swing.JButton manageExpenditureReasonButton;
    private javax.swing.JButton manageIncomeButton;
    private javax.swing.JButton manageResponsibleButton;
    private javax.swing.JButton manageUserButton;
    private javax.swing.JButton manageaIncomeReasonButton;
    // End of variables declaration//GEN-END:variables
}
