/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UserController;
import functionalities.ComboSearch;
import functionalities.LoadCombo;
import functionalities.IdGenerator;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import functionalities.DataProtector;

/**
 *
 * @author Ershadi
 */
public class ManageUser extends javax.swing.JFrame {

    private IdGenerator idGenerator;
    private UserController userController;
    private DataProtector dataProtector;
    private LoadCombo comboBoxFunctions;
    private Object object[];
    private DefaultTableModel dtmForUser;
    private ComboSearch comboSearch1;
    private ComboSearch comboSearch2;

    /**
     * Creates new form ManageIncome
     */
    public ManageUser() {
        try {
            initComponents();

            idGenerator = new IdGenerator();
            userController = new UserController();
            dataProtector = new DataProtector();
            comboBoxFunctions = new LoadCombo();
            dtmForUser = (DefaultTableModel) userTable.getModel();
            comboSearch1 = new ComboSearch();
            comboSearch2 = new ComboSearch();

            add_userIdLabel.setText(idGenerator.generateId("uu"));

            delete_userIdRadioButton.setSelected(true);
            update_userIdRadioButton.setSelected(true);

            loadComboForUser();
            loadTableForUser();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        manageUserTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        delete_userIdLabel = new javax.swing.JLabel();
        delete_userButton = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        delete_userIdRadioButton = new javax.swing.JRadioButton();
        delete_userNameRadioButton = new javax.swing.JRadioButton();
        delete_userComboBox = new javax.swing.JComboBox();
        delete_userNameLabel = new javax.swing.JLabel();
        searchDelete_donatorAddressLabel = new javax.swing.JLabel();
        searchDelete_donatorPhoneLabel = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        delete_adminPasswordField = new javax.swing.JPasswordField();
        jPanel10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        add_userNameTextFiled = new javax.swing.JTextField();
        add_userIdLabel = new javax.swing.JLabel();
        save_userButton = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        add_passwordField = new javax.swing.JPasswordField();
        add_confirmPasswordField = new javax.swing.JPasswordField();
        jPanel11 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        update_userNameTextField = new javax.swing.JTextField();
        update_userIdLabel = new javax.swing.JLabel();
        update_userButton = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        update_userIdRadioButton = new javax.swing.JRadioButton();
        update_userNameRadioButton = new javax.swing.JRadioButton();
        update_userComboBox = new javax.swing.JComboBox();
        update_currentPasswordField = new javax.swing.JPasswordField();
        update_newPasswordField = new javax.swing.JPasswordField();
        jLabel41 = new javax.swing.JLabel();
        update_confirmPasswordField = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        manageUserTabbedPane.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Delete User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12))); // NOI18N

        jLabel13.setText("User id :");

        jLabel1.setText("User name :");

        delete_userButton.setText("Delete user");
        delete_userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_userButtonActionPerformed(evt);
            }
        });

        jLabel29.setText("Search from :");

        buttonGroup1.add(delete_userIdRadioButton);
        delete_userIdRadioButton.setText("User id");
        delete_userIdRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_userIdRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(delete_userNameRadioButton);
        delete_userNameRadioButton.setText("User name");
        delete_userNameRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_userNameRadioButtonActionPerformed(evt);
            }
        });

        delete_userComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_userComboBoxActionPerformed(evt);
            }
        });

        jLabel38.setText("Admin password :");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(searchDelete_donatorPhoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(47, 47, 47)
                        .addComponent(delete_adminPasswordField)
                        .addGap(656, 656, 656))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel1))
                                .addGap(82, 82, 82)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(delete_userIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                                    .addComponent(delete_userNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(delete_userButton)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel29)
                                        .addGap(18, 18, 18)
                                        .addComponent(delete_userIdRadioButton)
                                        .addGap(18, 18, 18)
                                        .addComponent(delete_userNameRadioButton)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(delete_userComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchDelete_donatorAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(delete_userIdRadioButton)
                    .addComponent(delete_userNameRadioButton)
                    .addComponent(delete_userComboBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(delete_adminPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(searchDelete_donatorAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delete_userIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(delete_userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(delete_userButton)))
                .addGap(18, 18, 18)
                .addComponent(searchDelete_donatorPhoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Save New User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12))); // NOI18N

        jLabel17.setText("User id :");

        jLabel18.setText("User name :");

        jLabel19.setText("Password :");

        add_userIdLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        save_userButton.setText("Save user");
        save_userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_userButtonActionPerformed(evt);
            }
        });

        jLabel28.setText("Confirm password :");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel19))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(add_userNameTextFiled, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                            .addComponent(add_passwordField)
                            .addComponent(add_confirmPasswordField)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                                .addComponent(add_userIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(save_userButton)
                .addGap(24, 24, 24))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_userIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(add_userNameTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(add_passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add_confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(18, 18, 18)
                .addComponent(save_userButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update User", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12))); // NOI18N

        jLabel33.setText("User id :");

        jLabel36.setText("User name :");

        jLabel37.setText("Current password :");

        update_userIdLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        update_userButton.setText("Update user");
        update_userButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_userButtonActionPerformed(evt);
            }
        });

        jLabel39.setText("New password :");

        jLabel40.setText("Search from :");

        buttonGroup2.add(update_userIdRadioButton);
        update_userIdRadioButton.setText("User id");
        update_userIdRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_userIdRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(update_userNameRadioButton);
        update_userNameRadioButton.setText("User name");
        update_userNameRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_userNameRadioButtonActionPerformed(evt);
            }
        });

        update_userComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_userComboBoxActionPerformed(evt);
            }
        });

        jLabel41.setText("Confirm new password :");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addGap(18, 18, 18)
                        .addComponent(update_userIdRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(update_userNameRadioButton)
                        .addGap(26, 26, 26)
                        .addComponent(update_userComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(jLabel39))
                        .addGap(47, 47, 47)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(update_confirmPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                            .addComponent(update_newPasswordField)
                            .addComponent(update_userNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                            .addComponent(update_currentPasswordField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(update_userButton))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel36)
                            .addComponent(jLabel41))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(100, 100, 100)
                        .addComponent(update_userIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(update_userIdRadioButton)
                    .addComponent(update_userNameRadioButton)
                    .addComponent(update_userComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update_userIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(update_userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(update_currentPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(update_newPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel41)
                    .addComponent(update_confirmPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(update_userButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1120, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(193, Short.MAX_VALUE))
        );

        manageUserTabbedPane.addTab("Manage Users", jPanel1);

        userTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User id", "User name"
            }
        ));
        jScrollPane1.setViewportView(userTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1040, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        manageUserTabbedPane.addTab("Search All Users", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageUserTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(manageUserTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 255, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save_userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_userButtonActionPerformed
        try {
            if (!add_userNameTextFiled.getText().isEmpty() && !add_passwordField.getText().isEmpty() && !add_confirmPasswordField.getText().isEmpty()) {
                if (add_passwordField.getText().equals(add_confirmPasswordField.getText())) {
                    String user_password = add_passwordField.getText();
                    String encrypted_password = dataProtector.encrypt(user_password, "a", 3);

                    int result = userController.addUser(add_userIdLabel.getText(), add_userNameTextFiled.getText(), encrypted_password);

                    if (result == 1) {
                        JOptionPane.showMessageDialog(rootPane, "User saved successfully.");

                        add_userIdLabel.setText(idGenerator.generateId("uu"));
                        add_userNameTextFiled.setText(null);
                        add_passwordField.setText(null);
                        add_confirmPasswordField.setText(null);

                        loadComboForUser();
                        loadTableForUser();
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "User saving failed. Please retry saving with corrrect details.");
                    }

                } else {
                    JOptionPane.showMessageDialog(rootPane, "Passwords do not match. Please enter them again");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "None of the fields cannot be null. Please recheck before you save user.");
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_save_userButtonActionPerformed

    private void delete_userIdRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_userIdRadioButtonActionPerformed
        try {
            loadComboForUser();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_delete_userIdRadioButtonActionPerformed

    private void delete_userNameRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_userNameRadioButtonActionPerformed
        try {
            loadComboForUser();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_delete_userNameRadioButtonActionPerformed

    private void delete_userComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_userComboBoxActionPerformed
        try {
            if (delete_userIdRadioButton.isSelected()) {
                object = userController.searchUser("user_id", delete_userComboBox.getSelectedItem() + "");
            } else if (delete_userNameRadioButton.isSelected()) {
                object = userController.searchUser("user_name", delete_userComboBox.getSelectedItem() + "");
            }
            delete_userIdLabel.setText((String) object[0]);
            delete_userNameLabel.setText((String) object[1]);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_delete_userComboBoxActionPerformed

    private void delete_userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_userButtonActionPerformed
        try {
            object = userController.searchUser("user_id", "uu1");
            String decrypt_password = dataProtector.decrypt((String) object[2], "a", 3);

            if (delete_adminPasswordField.getText().equals(decrypt_password)) {
                if (!"uu1".equals(delete_userIdLabel.getText())) {
                    int result = userController.deleteUser(delete_userIdLabel.getText());

                    if (result == 1) {
                        JOptionPane.showMessageDialog(rootPane, "User deleted successfully.");

                        loadComboForUser();
                        loadTableForUser();
                        add_userIdLabel.setText(idGenerator.generateId("uu"));
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Unable to delete the selected user.");
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "You cannot delete administrator from the system.");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Please enter correct admin password to delete user.");
            }

        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_delete_userButtonActionPerformed

    private void update_userIdRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_userIdRadioButtonActionPerformed
        try {
            loadComboForUser();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_update_userIdRadioButtonActionPerformed

    private void update_userNameRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_userNameRadioButtonActionPerformed
        try {
            loadComboForUser();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_update_userNameRadioButtonActionPerformed

    private void update_userComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_userComboBoxActionPerformed
        try {
            if (update_userIdRadioButton.isSelected()) {
                object = userController.searchUser("user_id", update_userComboBox.getSelectedItem() + "");
            } else if (delete_userNameRadioButton.isSelected()) {
                object = userController.searchUser("user_name", update_userComboBox.getSelectedItem() + "");
            }
            update_userIdLabel.setText((String) object[0]);
            update_userNameTextField.setText((String) object[1]);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_update_userComboBoxActionPerformed

    private void update_userButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_userButtonActionPerformed
        try {
            if (update_userNameTextField.getText() != null && update_currentPasswordField.getText() != null
                    && update_newPasswordField.getText() != null && update_confirmPasswordField.getText() != null) {
                if (update_newPasswordField.getText().equals(update_confirmPasswordField.getText())) {
                    object = userController.searchUser("user_id", update_userIdLabel.getText());

                    String decrypt_password = dataProtector.decrypt((String) object[2], "a", 3);

                    if (decrypt_password.equals(update_currentPasswordField.getText())) {
                        String encrypt_password = dataProtector.encrypt(update_newPasswordField.getText(), "a", 3);
                        int result = userController.updateUser(update_userIdLabel.getText(), update_userNameTextField.getText(), encrypt_password);

                        if (result == 1) {
                            JOptionPane.showMessageDialog(rootPane, "User updated successfully.");

                            loadComboForUser();
                            loadTableForUser();
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "User failed to update.");
                        }
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Current password is wrong. Please enter it again.");
                    }
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Passwords do not match. Please enter them again");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "None of the fields cannot be null. Please recheck before you update user.");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(ManageUser.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_update_userButtonActionPerformed

    private void loadComboForUser() throws ClassNotFoundException, SQLException {
        if (delete_userIdRadioButton.isSelected()) {
            delete_userComboBox.removeAllItems();
            comboBoxFunctions.loadCombo(delete_userComboBox, "user", "user_id");
            comboSearch1.setSearchableCombo(delete_userComboBox, true, "No such user available");
        } else if (delete_userNameRadioButton.isSelected()) {
            delete_userComboBox.removeAllItems();
            comboBoxFunctions.loadCombo(delete_userComboBox, "user", "user_name");
            comboSearch2.setSearchableCombo(delete_userComboBox, true, "No such user available");
        }

        if (update_userIdRadioButton.isSelected()) {
            update_userComboBox.removeAllItems();
            comboBoxFunctions.loadCombo(update_userComboBox, "user", "user_id");
            comboSearch1.setSearchableCombo(update_userComboBox, true, "No such user available");
        } else if (update_userNameRadioButton.isSelected()) {
            update_userComboBox.removeAllItems();
            comboBoxFunctions.loadCombo(update_userComboBox, "user", "user_name");
            comboSearch2.setSearchableCombo(update_userComboBox, true, "No such user available");
        }
    }

    private void loadTableForUser() throws ClassNotFoundException, SQLException {
        dtmForUser.setRowCount(0);
        ArrayList<Object[]> arrayList = userController.searchAllUser();

        for (int i = 0; i < arrayList.size(); i++) {
            dtmForUser.addRow(arrayList.get(i));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField add_confirmPasswordField;
    private javax.swing.JPasswordField add_passwordField;
    private javax.swing.JLabel add_userIdLabel;
    private javax.swing.JTextField add_userNameTextFiled;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPasswordField delete_adminPasswordField;
    private javax.swing.JButton delete_userButton;
    private javax.swing.JComboBox delete_userComboBox;
    private javax.swing.JLabel delete_userIdLabel;
    private javax.swing.JRadioButton delete_userIdRadioButton;
    private javax.swing.JLabel delete_userNameLabel;
    private javax.swing.JRadioButton delete_userNameRadioButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane manageUserTabbedPane;
    private javax.swing.JButton save_userButton;
    private javax.swing.JLabel searchDelete_donatorAddressLabel;
    private javax.swing.JLabel searchDelete_donatorPhoneLabel;
    private javax.swing.JPasswordField update_confirmPasswordField;
    private javax.swing.JPasswordField update_currentPasswordField;
    private javax.swing.JPasswordField update_newPasswordField;
    private javax.swing.JButton update_userButton;
    private javax.swing.JComboBox update_userComboBox;
    private javax.swing.JLabel update_userIdLabel;
    private javax.swing.JRadioButton update_userIdRadioButton;
    private javax.swing.JRadioButton update_userNameRadioButton;
    private javax.swing.JTextField update_userNameTextField;
    private javax.swing.JTable userTable;
    // End of variables declaration//GEN-END:variables
}
