/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ResponsibleController;
import functionalities.ComboSearch;
import functionalities.LoadCombo;
import functionalities.IdGenerator;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ershadi
 */
public class ManageResponsible extends javax.swing.JFrame {

    private IdGenerator idGenerator;
    private ResponsibleController responsibleController;
    private LoadCombo comboBoxFunctions;
    private Object object[];
    private DefaultTableModel dtmForResponsible;
    ComboSearch comboSearch1;
    ComboSearch comboSearch2;

    /**
     * Creates new form ManageIncome
     */
    public ManageResponsible() {
        try {
            initComponents();

            idGenerator = new IdGenerator();
            responsibleController = new ResponsibleController();
            comboBoxFunctions = new LoadCombo();
            dtmForResponsible = (DefaultTableModel) responsibleTable.getModel();
            comboSearch1 = new ComboSearch();
            comboSearch2 = new ComboSearch();

            add_responsibleIdLabel.setText(idGenerator.generateId("rr"));

            searchDelete_responsibleIdRadioButton.setSelected(true);
            loadComboForResponsible();
            loadTableForResponsible();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageResponsible.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        manageResponsiblePanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        add_responsibleIdLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        add_responsibleNameText = new javax.swing.JTextField();
        save_responsibleButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        searchDelete_responsibleIdRadioButton = new javax.swing.JRadioButton();
        searchDelete_responsibleRadioButton = new javax.swing.JRadioButton();
        searchDelete_responsibleComboBox = new javax.swing.JComboBox();
        searchDelete_responsibleFirstLabel = new javax.swing.JLabel();
        searchDelete_responsibleSecondLabel = new javax.swing.JLabel();
        delete_responsibleButton = new javax.swing.JButton();
        searchDelete_responsibleLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        update_responsibleIdComboBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        update_responsibleNameTextField = new javax.swing.JTextField();
        update_responsibleButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        responsibleTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add New Responsible", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12))); // NOI18N

        jLabel1.setText("Responsible id :");

        add_responsibleIdLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel3.setText("Responsible name :");

        save_responsibleButton.setText("Save responsible");
        save_responsibleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_responsibleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add_responsibleNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                            .addComponent(add_responsibleIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(save_responsibleButton)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_responsibleIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(add_responsibleNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(save_responsibleButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search and Delete Responsible", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12))); // NOI18N

        jLabel7.setText("Search from :");

        buttonGroup1.add(searchDelete_responsibleIdRadioButton);
        searchDelete_responsibleIdRadioButton.setText("Responsible id");
        searchDelete_responsibleIdRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDelete_responsibleIdRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(searchDelete_responsibleRadioButton);
        searchDelete_responsibleRadioButton.setText("Responsible name");
        searchDelete_responsibleRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDelete_responsibleRadioButtonActionPerformed(evt);
            }
        });

        searchDelete_responsibleComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDelete_responsibleComboBoxActionPerformed(evt);
            }
        });

        searchDelete_responsibleFirstLabel.setText("Responsible id :");

        searchDelete_responsibleSecondLabel.setText("Responsible name :");

        delete_responsibleButton.setText("Delete responsble");
        delete_responsibleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_responsibleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(searchDelete_responsibleIdRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(searchDelete_responsibleRadioButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchDelete_responsibleFirstLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchDelete_responsibleSecondLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchDelete_responsibleComboBox, 0, 310, Short.MAX_VALUE)
                            .addComponent(searchDelete_responsibleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(97, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(delete_responsibleButton)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(searchDelete_responsibleIdRadioButton)
                    .addComponent(searchDelete_responsibleRadioButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchDelete_responsibleComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchDelete_responsibleFirstLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchDelete_responsibleSecondLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchDelete_responsibleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(delete_responsibleButton)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Responsible", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12))); // NOI18N

        update_responsibleIdComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_responsibleIdComboBoxActionPerformed(evt);
            }
        });

        jLabel5.setText("Responsible id :");

        jLabel6.setText("Responsible Name :");

        update_responsibleButton.setText("Update responsible");
        update_responsibleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_responsibleButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update_responsibleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(update_responsibleIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(update_responsibleButton)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_responsibleIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(update_responsibleNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(update_responsibleButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        responsibleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Responsible id", "Responsible Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(responsibleTable);

        javax.swing.GroupLayout manageResponsiblePanelLayout = new javax.swing.GroupLayout(manageResponsiblePanel);
        manageResponsiblePanel.setLayout(manageResponsiblePanelLayout);
        manageResponsiblePanelLayout.setHorizontalGroup(
            manageResponsiblePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageResponsiblePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageResponsiblePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageResponsiblePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 476, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        manageResponsiblePanelLayout.setVerticalGroup(
            manageResponsiblePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageResponsiblePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageResponsiblePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 605, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(manageResponsiblePanelLayout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(303, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(manageResponsiblePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1203, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(manageResponsiblePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save_responsibleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_responsibleButtonActionPerformed
        try {
            if (!add_responsibleNameText.getText().isEmpty()) {
                int result = responsibleController.addResponsible(add_responsibleIdLabel.getText(), add_responsibleNameText.getText());

                if (result == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Responsible saved successfully.");

                    add_responsibleIdLabel.setText(idGenerator.generateId("rr"));
                    add_responsibleNameText.setText(null);

                    loadComboForResponsible();
                    loadTableForResponsible();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Responsible saving failed. Please retry saving with corrrect details.");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "None of the fields cannot be null. Please recheck before you save respomsible.");
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageResponsible.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_save_responsibleButtonActionPerformed

    private void searchDelete_responsibleIdRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDelete_responsibleIdRadioButtonActionPerformed
        try {
            searchDelete_responsibleFirstLabel.setText("Responsible id :");
            searchDelete_responsibleSecondLabel.setText("Responsible name :");

            loadComboForResponsible();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageResponsible.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchDelete_responsibleIdRadioButtonActionPerformed

    private void searchDelete_responsibleRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDelete_responsibleRadioButtonActionPerformed
        try {
            searchDelete_responsibleFirstLabel.setText("Responsible name :");
            searchDelete_responsibleSecondLabel.setText("Responsible id :");

            loadComboForResponsible();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageResponsible.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchDelete_responsibleRadioButtonActionPerformed

    private void searchDelete_responsibleComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDelete_responsibleComboBoxActionPerformed
        try {
            switch (searchDelete_responsibleFirstLabel.getText()) {
                case "Responsible id :":
                    object = responsibleController.searchResponsible("responsible_id", searchDelete_responsibleComboBox.getSelectedItem() + "");
                    searchDelete_responsibleLabel.setText((String) object[1]);
                    break;
                case "Responsible name :":
                    object = responsibleController.searchResponsible("responsible_name", searchDelete_responsibleComboBox.getSelectedItem() + "");
                    searchDelete_responsibleLabel.setText((String) object[0]);
                    break;
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageResponsible.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchDelete_responsibleComboBoxActionPerformed

    private void delete_responsibleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_responsibleButtonActionPerformed
        try {
            int result = 0;
            switch (searchDelete_responsibleFirstLabel.getText()) {
                case "Responsible id :":
                    result = responsibleController.deleteResponsible(searchDelete_responsibleComboBox.getSelectedItem() + "");
                    break;
                case "Responsible name :":
                    result = responsibleController.deleteResponsible(searchDelete_responsibleLabel.getText());
                    break;
            }

            if (result == 1) {
                JOptionPane.showMessageDialog(rootPane, "Responsible deleted successfully.");

                loadComboForResponsible();
                loadTableForResponsible();
                add_responsibleIdLabel.setText(idGenerator.generateId("rr"));
            } else {
                JOptionPane.showMessageDialog(rootPane, "Unable to delete the selected responsible.");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageResponsible.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_delete_responsibleButtonActionPerformed

    private void update_responsibleIdComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_responsibleIdComboBoxActionPerformed
        try {
            object = responsibleController.searchResponsible("responsible_id", searchDelete_responsibleComboBox.getSelectedItem() + "");
            update_responsibleNameTextField.setText((String) object[1]);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageResponsible.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_update_responsibleIdComboBoxActionPerformed

    private void update_responsibleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_responsibleButtonActionPerformed
        try {
            if (update_responsibleNameTextField.getText() != null) {
                int result = responsibleController.updateResponsible(update_responsibleIdComboBox.getSelectedItem() + "", update_responsibleNameTextField.getText());

                if (result == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Responsible updated successfully.");

                    loadComboForResponsible();
                    loadTableForResponsible();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Responsible failed to update.");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "None of the fields cannot be null. Please recheck before you update responsible.");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageResponsible.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_update_responsibleButtonActionPerformed

    private void loadComboForResponsible() throws ClassNotFoundException, SQLException {
        switch (searchDelete_responsibleFirstLabel.getText()) {
            case "Responsible id :":
                searchDelete_responsibleComboBox.removeAllItems();
                comboBoxFunctions.loadCombo(searchDelete_responsibleComboBox, "responsible", "responsible_id");
                comboSearch1.setSearchableCombo(searchDelete_responsibleComboBox, true, "No such responsible available");
                break;
            case "Responsible name :":
                searchDelete_responsibleComboBox.removeAllItems();
                comboBoxFunctions.loadCombo(searchDelete_responsibleComboBox, "responsible", "responsible_name");
                comboSearch1.setSearchableCombo(searchDelete_responsibleComboBox, true, "No such responsible available");
                break;
        }

        update_responsibleIdComboBox.removeAllItems();
        comboBoxFunctions.loadCombo(update_responsibleIdComboBox, "responsible", "responsible_id");
        comboSearch2.setSearchableCombo(update_responsibleIdComboBox, true, "No such iresponsible available");
    }

    private void loadTableForResponsible() throws ClassNotFoundException, SQLException {
        dtmForResponsible.setRowCount(0);
        ArrayList<Object[]> arrayList = responsibleController.searchAllResponsible();

        for (int i = 0; i < arrayList.size(); i++) {
            dtmForResponsible.addRow(arrayList.get(i));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageResponsible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageResponsible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageResponsible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageResponsible.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageResponsible().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_responsibleIdLabel;
    private javax.swing.JTextField add_responsibleNameText;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton delete_responsibleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JPanel manageResponsiblePanel;
    private javax.swing.JTable responsibleTable;
    private javax.swing.JButton save_responsibleButton;
    private javax.swing.JComboBox searchDelete_responsibleComboBox;
    private javax.swing.JLabel searchDelete_responsibleFirstLabel;
    private javax.swing.JRadioButton searchDelete_responsibleIdRadioButton;
    private javax.swing.JLabel searchDelete_responsibleLabel;
    private javax.swing.JRadioButton searchDelete_responsibleRadioButton;
    private javax.swing.JLabel searchDelete_responsibleSecondLabel;
    private javax.swing.JButton update_responsibleButton;
    private javax.swing.JComboBox update_responsibleIdComboBox;
    private javax.swing.JTextField update_responsibleNameTextField;
    // End of variables declaration//GEN-END:variables
}
