/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.DonatorController;
import functionalities.ComboSearch;
import functionalities.LoadCombo;
import functionalities.IdGenerator;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ershadi
 */
public class ManageDonator extends javax.swing.JFrame {

    private IdGenerator idGenerator;
    private DonatorController donatorController;
    private LoadCombo comboBoxFunctions;
    private Object object[];
    private DefaultTableModel dtmForDonator;
    private ComboSearch comboSearch1;
    private ComboSearch comboSearch2;

    /**
     * Creates new form ManageIncome
     */
    public ManageDonator() {
        try {
            initComponents();

            idGenerator = new IdGenerator();
            donatorController = new DonatorController();
            comboBoxFunctions = new LoadCombo();
            dtmForDonator = (DefaultTableModel) donatorTable.getModel();
            comboSearch1 = new ComboSearch();
            comboSearch2 = new ComboSearch();

            add_donatorIdLabel.setText(idGenerator.generateId("dd"));

            searchDelete_donatorIdRadioButton.setSelected(true);
            update_donatorIdRadioButton.setSelected(true);

            loadComboForDonator();
            loadTableForDonator();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageDonator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        manageDonatorTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        searchDelete_donatorIdLabel = new javax.swing.JLabel();
        searchDelete_donatorButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        searchDelete_donatorIdRadioButton = new javax.swing.JRadioButton();
        searchDelete_donatorNameRadioButton = new javax.swing.JRadioButton();
        searchDelete_donatorComboBox = new javax.swing.JComboBox();
        searchDelete_donatorNameLabel = new javax.swing.JLabel();
        searchDelete_donatorAddressLabel = new javax.swing.JLabel();
        searchDelete_donatorPhoneLabel = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        add_donatorPhoneTextField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        add_donatorAddressTextArea = new javax.swing.JTextArea();
        add_donatorNameTextFiled = new javax.swing.JTextField();
        add_donatorIdLabel = new javax.swing.JLabel();
        save_donatorButton = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        update_donatorPhoneTextField = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        update_donatorAddressTextArea = new javax.swing.JTextArea();
        update_donatorNameTextField = new javax.swing.JTextField();
        update_donatorIdLabel = new javax.swing.JLabel();
        update_donatorButton = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        update_donatorIdRadioButton = new javax.swing.JRadioButton();
        update_donatorNameRadioButton = new javax.swing.JRadioButton();
        update_donatorComboBox = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        donatorTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        manageDonatorTabbedPane.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search and Delete Donator", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12))); // NOI18N

        jLabel13.setText("Donatior id :");

        jLabel1.setText("Donator name :");

        jLabel2.setText("Address :");

        searchDelete_donatorButton.setText("Delete donator");
        searchDelete_donatorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDelete_donatorButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Telephone number :");

        jLabel29.setText("Search from :");

        buttonGroup1.add(searchDelete_donatorIdRadioButton);
        searchDelete_donatorIdRadioButton.setText("Donator id");
        searchDelete_donatorIdRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDelete_donatorIdRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(searchDelete_donatorNameRadioButton);
        searchDelete_donatorNameRadioButton.setText("Donator name");
        searchDelete_donatorNameRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDelete_donatorNameRadioButtonActionPerformed(evt);
            }
        });

        searchDelete_donatorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDelete_donatorComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchDelete_donatorIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(109, 109, 109))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(searchDelete_donatorNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(searchDelete_donatorPhoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(18, 18, 18)
                        .addComponent(searchDelete_donatorIdRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(searchDelete_donatorNameRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchDelete_donatorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(searchDelete_donatorAddressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(searchDelete_donatorButton)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(searchDelete_donatorIdRadioButton)
                    .addComponent(searchDelete_donatorNameRadioButton)
                    .addComponent(searchDelete_donatorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(searchDelete_donatorIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchDelete_donatorNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchDelete_donatorAddressLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchDelete_donatorPhoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(searchDelete_donatorButton)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Save New Donator", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12))); // NOI18N

        jLabel17.setText("Donatior id :");

        jLabel18.setText("Donator name :");

        jLabel19.setText("Address :");

        add_donatorAddressTextArea.setColumns(20);
        add_donatorAddressTextArea.setRows(5);
        jScrollPane3.setViewportView(add_donatorAddressTextArea);

        add_donatorIdLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        save_donatorButton.setText("Save donator");
        save_donatorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_donatorButtonActionPerformed(evt);
            }
        });

        jLabel28.setText("Telephone number :");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jLabel19))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add_donatorPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_donatorNameTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(save_donatorButton)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(add_donatorIdLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(76, 76, 76)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_donatorIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(add_donatorNameTextFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(add_donatorPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(save_donatorButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Donator", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12))); // NOI18N

        jLabel33.setText("Donatior id :");

        jLabel36.setText("Donator name :");

        jLabel37.setText("Address :");

        update_donatorAddressTextArea.setColumns(20);
        update_donatorAddressTextArea.setRows(5);
        jScrollPane4.setViewportView(update_donatorAddressTextArea);

        update_donatorIdLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        update_donatorButton.setText("Update donator");
        update_donatorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_donatorButtonActionPerformed(evt);
            }
        });

        jLabel39.setText("Telephone number :");

        jLabel40.setText("Search from :");

        buttonGroup2.add(update_donatorIdRadioButton);
        update_donatorIdRadioButton.setText("Donator id");
        update_donatorIdRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_donatorIdRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(update_donatorNameRadioButton);
        update_donatorNameRadioButton.setText("Donator name");
        update_donatorNameRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_donatorNameRadioButtonActionPerformed(evt);
            }
        });

        update_donatorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_donatorComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(update_donatorButton))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(81, 81, 81)
                        .addComponent(update_donatorIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addGap(18, 18, 18)
                        .addComponent(update_donatorIdRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(update_donatorNameRadioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(update_donatorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel39)
                                    .addComponent(jLabel37))
                                .addGap(44, 44, 44)
                                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(update_donatorPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(update_donatorNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel36))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel40)
                    .addComponent(update_donatorIdRadioButton)
                    .addComponent(update_donatorNameRadioButton)
                    .addComponent(update_donatorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(update_donatorIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(update_donatorNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel37)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update_donatorPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addGap(18, 18, 18)
                .addComponent(update_donatorButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1117, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );

        manageDonatorTabbedPane.addTab("Manage Donator", jPanel1);

        donatorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Donator id", "Donator name", "Address", "Telephone number"
            }
        ));
        jScrollPane1.setViewportView(donatorTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1040, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        manageDonatorTabbedPane.addTab("Search All Donators", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageDonatorTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(manageDonatorTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 255, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save_donatorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_donatorButtonActionPerformed
        try {
            if (!add_donatorNameTextFiled.getText().isEmpty() && !add_donatorAddressTextArea.getText().isEmpty()
                    && !add_donatorPhoneTextField.getText().isEmpty()) {
                int result = donatorController.addDonator(add_donatorIdLabel.getText(), add_donatorNameTextFiled.getText(), add_donatorAddressTextArea.getText(), add_donatorPhoneTextField.getText());

                if (result == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Donator saved successfully.");

                    add_donatorIdLabel.setText(idGenerator.generateId("dd"));
                    add_donatorNameTextFiled.setText(null);
                    add_donatorAddressTextArea.setText(null);
                    add_donatorPhoneTextField.setText(null);

                    loadComboForDonator();
                    loadTableForDonator();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Donator saving failed. Please retry saving with corrrect details.");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "None of the fields cannot be null. Please recheck before you save donator.");
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_save_donatorButtonActionPerformed

    private void searchDelete_donatorIdRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDelete_donatorIdRadioButtonActionPerformed
        try {
            loadComboForDonator();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageDonator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchDelete_donatorIdRadioButtonActionPerformed

    private void searchDelete_donatorNameRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDelete_donatorNameRadioButtonActionPerformed
        try {
            loadComboForDonator();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageDonator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchDelete_donatorNameRadioButtonActionPerformed

    private void searchDelete_donatorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDelete_donatorComboBoxActionPerformed
        try {
            if (searchDelete_donatorIdRadioButton.isSelected()) {
                object = donatorController.searchDonator("donator_id", searchDelete_donatorComboBox.getSelectedItem() + "");
            } else if (searchDelete_donatorNameRadioButton.isSelected()) {
                object = donatorController.searchDonator("donator_name", searchDelete_donatorComboBox.getSelectedItem() + "");
            }
            searchDelete_donatorIdLabel.setText((String) object[0]);
            searchDelete_donatorNameLabel.setText((String) object[1]);
            searchDelete_donatorAddressLabel.setText((String) object[2]);
            searchDelete_donatorPhoneLabel.setText((String) object[3]);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageDonator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchDelete_donatorComboBoxActionPerformed

    private void searchDelete_donatorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDelete_donatorButtonActionPerformed
        try {
            int result = donatorController.deleteDonator(searchDelete_donatorIdLabel.getText());

            if (result == 1) {
                JOptionPane.showMessageDialog(rootPane, "Donator deleted successfully.");

                loadComboForDonator();
                loadTableForDonator();
                add_donatorIdLabel.setText(idGenerator.generateId("dd"));
            } else {
                JOptionPane.showMessageDialog(rootPane, "Unable to delete the selected donator.");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchDelete_donatorButtonActionPerformed

    private void update_donatorIdRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_donatorIdRadioButtonActionPerformed
        try {
            loadComboForDonator();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageDonator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_update_donatorIdRadioButtonActionPerformed

    private void update_donatorNameRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_donatorNameRadioButtonActionPerformed
        try {
            loadComboForDonator();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageDonator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_update_donatorNameRadioButtonActionPerformed

    private void update_donatorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_donatorComboBoxActionPerformed
        try {
            if (update_donatorIdRadioButton.isSelected()) {
                object = donatorController.searchDonator("donator_id", update_donatorComboBox.getSelectedItem() + "");
            } else if (searchDelete_donatorNameRadioButton.isSelected()) {
                object = donatorController.searchDonator("donator_name", update_donatorComboBox.getSelectedItem() + "");
            }
            update_donatorIdLabel.setText((String) object[0]);
            update_donatorNameTextField.setText((String) object[1]);
            update_donatorAddressTextArea.setText((String) object[2]);
            update_donatorPhoneTextField.setText((String) object[3]);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageDonator.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_update_donatorComboBoxActionPerformed

    private void update_donatorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_donatorButtonActionPerformed
        try {
            if (update_donatorNameTextField.getText() != null && update_donatorAddressTextArea.getText() != null
                    && update_donatorPhoneTextField.getText() != null) {
                int result = donatorController.updateDonator(update_donatorIdLabel.getText(), update_donatorNameTextField.getText(), update_donatorAddressTextArea.getText(), update_donatorPhoneTextField.getText());

                if (result == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Donator updated successfully.");

                    loadComboForDonator();
                    loadTableForDonator();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Donator failed to update.");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "None of the fields cannot be null. Please recheck before you update donator.");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_update_donatorButtonActionPerformed

    private void loadComboForDonator() throws ClassNotFoundException, SQLException {
        if (searchDelete_donatorIdRadioButton.isSelected()) {
            searchDelete_donatorComboBox.removeAllItems();
            comboBoxFunctions.loadCombo(searchDelete_donatorComboBox, "donator", "donator_id");
            comboSearch1.setSearchableCombo(searchDelete_donatorComboBox, true, "No such donator available");
        } else if (searchDelete_donatorNameRadioButton.isSelected()) {
            searchDelete_donatorComboBox.removeAllItems();
            comboBoxFunctions.loadCombo(searchDelete_donatorComboBox, "donator", "donator_name");
            comboSearch1.setSearchableCombo(searchDelete_donatorComboBox, true, "No such donator available");
        }

        if (update_donatorIdRadioButton.isSelected()) {
            update_donatorComboBox.removeAllItems();
            comboBoxFunctions.loadCombo(update_donatorComboBox, "donator", "donator_id");
            comboSearch2.setSearchableCombo(update_donatorComboBox, true, "No such donator available");
        } else if (update_donatorNameRadioButton.isSelected()) {
            update_donatorComboBox.removeAllItems();
            comboBoxFunctions.loadCombo(update_donatorComboBox, "donator", "donator_name");
            comboSearch2.setSearchableCombo(update_donatorComboBox, true, "No such donator available");
        }
    }

    private void loadTableForDonator() throws ClassNotFoundException, SQLException {
        dtmForDonator.setRowCount(0);
        ArrayList<Object[]> arrayList = donatorController.searchAllDonator();

        for (int i = 0; i < arrayList.size(); i++) {
            dtmForDonator.addRow(arrayList.get(i));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageDonator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageDonator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageDonator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageDonator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageDonator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea add_donatorAddressTextArea;
    private javax.swing.JLabel add_donatorIdLabel;
    private javax.swing.JTextField add_donatorNameTextFiled;
    private javax.swing.JTextField add_donatorPhoneTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTable donatorTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JTabbedPane manageDonatorTabbedPane;
    private javax.swing.JButton save_donatorButton;
    private javax.swing.JLabel searchDelete_donatorAddressLabel;
    private javax.swing.JButton searchDelete_donatorButton;
    private javax.swing.JComboBox searchDelete_donatorComboBox;
    private javax.swing.JLabel searchDelete_donatorIdLabel;
    private javax.swing.JRadioButton searchDelete_donatorIdRadioButton;
    private javax.swing.JLabel searchDelete_donatorNameLabel;
    private javax.swing.JRadioButton searchDelete_donatorNameRadioButton;
    private javax.swing.JLabel searchDelete_donatorPhoneLabel;
    private javax.swing.JTextArea update_donatorAddressTextArea;
    private javax.swing.JButton update_donatorButton;
    private javax.swing.JComboBox update_donatorComboBox;
    private javax.swing.JLabel update_donatorIdLabel;
    private javax.swing.JRadioButton update_donatorIdRadioButton;
    private javax.swing.JRadioButton update_donatorNameRadioButton;
    private javax.swing.JTextField update_donatorNameTextField;
    private javax.swing.JTextField update_donatorPhoneTextField;
    // End of variables declaration//GEN-END:variables
}
