/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ExpenditureReasonController;
import controller.IncomeReasonController;
import functionalities.ComboSearch;
import functionalities.IdGenerator;
import functionalities.LoadCombo;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ershadi
 */
public class ManageIncomeAndExpenditureReason extends javax.swing.JFrame {

    private IdGenerator idGenerator;
    private IncomeReasonController incomeReasonController;
    private ExpenditureReasonController expenditureReasonController;
    private LoadCombo comboBoxFunctions;
    private Object object[];
    private DefaultTableModel dtmForIncomeReason;
    private DefaultTableModel dtmForExpenditureReason;
    private ComboSearch comboSearch1;
    private ComboSearch comboSearch2;
    private ComboSearch comboSearch3;
    private ComboSearch comboSearch4;

    /**
     * Creates new form ManageIncome
     */
    public ManageIncomeAndExpenditureReason() {
        try {
            initComponents();

            idGenerator = new IdGenerator();
            incomeReasonController = new IncomeReasonController();
            expenditureReasonController = new ExpenditureReasonController();
            comboBoxFunctions = new LoadCombo();
            dtmForIncomeReason = (DefaultTableModel) incomeReasonTable.getModel();
            dtmForExpenditureReason = (DefaultTableModel) expenditureReasonTable.getModel();
            comboSearch1 = new ComboSearch();
            comboSearch2 = new ComboSearch();
            comboSearch3 = new ComboSearch();
            comboSearch4 = new ComboSearch();

            add_incomeExpenditureIdLabel.setText(idGenerator.generateId("ir"));
            add_expenditureIdLabel.setText(idGenerator.generateId("er"));

            searchDelete_incomeReasonIdRadioButton.setSelected(true);
            searchDelete_expenditureReasonIdRadioButton.setSelected(true);

            loadComboForIncomeReason();
            loadTableForIncomeReason();

            loadComboForExpenditureReason();
            loadTableForExpenditureReason();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        manageIncomeAndExpenditureReasonTabbedPane = new javax.swing.JTabbedPane();
        manageResponsiblePanel = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        add_incomeExpenditureIdLabel = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        add_incomeReasonText = new javax.swing.JTextField();
        save_incomeReasonButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        searchDelete_incomeReasonIdRadioButton = new javax.swing.JRadioButton();
        searchDelete_incomeReasonRadioButton = new javax.swing.JRadioButton();
        searchDelete_incomeReasonComboBox = new javax.swing.JComboBox();
        searchDelete_incomeReasonFirstLabel = new javax.swing.JLabel();
        searchDelete_incomeReasonSecondLabel = new javax.swing.JLabel();
        delete_incomeReasonButton = new javax.swing.JButton();
        searchDelete_incomeReasonLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        update_incomeReasonIdComboBox = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        update_incomeReasonTextField = new javax.swing.JTextField();
        update_incomeReasonButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        incomeReasonTable = new javax.swing.JTable();
        manageResponsiblePanel1 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        add_expenditureIdLabel = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        add_expenditureReasonText = new javax.swing.JTextField();
        save_expenditureReasonButton = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        searchDelete_expenditureReasonIdRadioButton = new javax.swing.JRadioButton();
        searchDelete_expenditureReasonRadioButton = new javax.swing.JRadioButton();
        searchDelete_expenditureReasonComboBox = new javax.swing.JComboBox();
        searchDelete_expenditureReasonFirstLabel = new javax.swing.JLabel();
        searchDelete_expenditureReasonSecondLabel = new javax.swing.JLabel();
        delete_expenditureReasonButton = new javax.swing.JButton();
        searchDelete_expenditureReasonLabel = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        update_expenditureReasonIdComboBox = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        update_expenditureReasonTextField = new javax.swing.JTextField();
        update_expenditureReasonButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        expenditureReasonTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        manageIncomeAndExpenditureReasonTabbedPane.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add New Income Reason", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12))); // NOI18N

        jLabel15.setText("Income id :");

        add_incomeExpenditureIdLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel17.setText("Income Reason :");

        save_incomeReasonButton.setText("Save income reason");
        save_incomeReasonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_incomeReasonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(save_incomeReasonButton))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel17))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add_incomeReasonText, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(add_incomeExpenditureIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_incomeExpenditureIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(add_incomeReasonText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(save_incomeReasonButton)
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search and Delete Income Reason", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12))); // NOI18N

        jLabel18.setText("Search from :");

        buttonGroup1.add(searchDelete_incomeReasonIdRadioButton);
        searchDelete_incomeReasonIdRadioButton.setText("Income id");
        searchDelete_incomeReasonIdRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDelete_incomeReasonIdRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(searchDelete_incomeReasonRadioButton);
        searchDelete_incomeReasonRadioButton.setText("Income reason");
        searchDelete_incomeReasonRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDelete_incomeReasonRadioButtonActionPerformed(evt);
            }
        });

        searchDelete_incomeReasonComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDelete_incomeReasonComboBoxActionPerformed(evt);
            }
        });

        searchDelete_incomeReasonFirstLabel.setText("Income reason id :");

        searchDelete_incomeReasonSecondLabel.setText("Income reason :");

        delete_incomeReasonButton.setText("Delete income reason");
        delete_incomeReasonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_incomeReasonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(searchDelete_incomeReasonIdRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(searchDelete_incomeReasonRadioButton))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchDelete_incomeReasonFirstLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchDelete_incomeReasonSecondLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchDelete_incomeReasonComboBox, 0, 396, Short.MAX_VALUE)
                            .addComponent(searchDelete_incomeReasonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(delete_incomeReasonButton)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(searchDelete_incomeReasonIdRadioButton)
                    .addComponent(searchDelete_incomeReasonRadioButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchDelete_incomeReasonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchDelete_incomeReasonFirstLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchDelete_incomeReasonSecondLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchDelete_incomeReasonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(delete_incomeReasonButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Income Reason", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12))); // NOI18N

        update_incomeReasonIdComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_incomeReasonIdComboBoxActionPerformed(evt);
            }
        });

        jLabel23.setText("Income reason id :");

        jLabel24.setText("Income reason :");

        update_incomeReasonButton.setText("Update income reason");
        update_incomeReasonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_incomeReasonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(update_incomeReasonTextField)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(update_incomeReasonIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(update_incomeReasonButton)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_incomeReasonIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(update_incomeReasonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(update_incomeReasonButton)
                .addContainerGap())
        );

        incomeReasonTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Income id", "Income reason"
            }
        ));
        jScrollPane2.setViewportView(incomeReasonTable);

        javax.swing.GroupLayout manageResponsiblePanelLayout = new javax.swing.GroupLayout(manageResponsiblePanel);
        manageResponsiblePanel.setLayout(manageResponsiblePanelLayout);
        manageResponsiblePanelLayout.setHorizontalGroup(
            manageResponsiblePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageResponsiblePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageResponsiblePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(819, Short.MAX_VALUE))
        );
        manageResponsiblePanelLayout.setVerticalGroup(
            manageResponsiblePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageResponsiblePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageResponsiblePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(manageResponsiblePanelLayout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(129, Short.MAX_VALUE))
        );

        manageIncomeAndExpenditureReasonTabbedPane.addTab("Manage Income Reason", manageResponsiblePanel);

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add New Expenditure Reason", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12))); // NOI18N

        jLabel20.setText("Expenditure id :");

        add_expenditureIdLabel.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N

        jLabel26.setText("Expenditure Reason :");

        save_expenditureReasonButton.setText("Save expenditure reason");
        save_expenditureReasonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_expenditureReasonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel26))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(add_expenditureReasonText, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                            .addComponent(add_expenditureIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(save_expenditureReasonButton)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_expenditureIdLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(add_expenditureReasonText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(save_expenditureReasonButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Search and Delete Expenditure Reason", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12))); // NOI18N

        jLabel27.setText("Search from :");

        buttonGroup2.add(searchDelete_expenditureReasonIdRadioButton);
        searchDelete_expenditureReasonIdRadioButton.setText("Expenditure id");
        searchDelete_expenditureReasonIdRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDelete_expenditureReasonIdRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(searchDelete_expenditureReasonRadioButton);
        searchDelete_expenditureReasonRadioButton.setText("Expenditure reason");
        searchDelete_expenditureReasonRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDelete_expenditureReasonRadioButtonActionPerformed(evt);
            }
        });

        searchDelete_expenditureReasonComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchDelete_expenditureReasonComboBoxActionPerformed(evt);
            }
        });

        searchDelete_expenditureReasonFirstLabel.setText("Expenditure reason id :");

        searchDelete_expenditureReasonSecondLabel.setText("Expenditure reason :");

        delete_expenditureReasonButton.setText("Delete expenditure reason");
        delete_expenditureReasonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_expenditureReasonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(18, 18, 18)
                        .addComponent(searchDelete_expenditureReasonIdRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(searchDelete_expenditureReasonRadioButton))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(searchDelete_expenditureReasonFirstLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchDelete_expenditureReasonSecondLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(searchDelete_expenditureReasonComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(searchDelete_expenditureReasonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 362, Short.MAX_VALUE)
                        .addComponent(delete_expenditureReasonButton)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(searchDelete_expenditureReasonIdRadioButton)
                    .addComponent(searchDelete_expenditureReasonRadioButton))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchDelete_expenditureReasonComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchDelete_expenditureReasonFirstLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(searchDelete_expenditureReasonSecondLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(searchDelete_expenditureReasonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delete_expenditureReasonButton)
                .addGap(18, 18, 18))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Update Expenpenditure Reason", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Trebuchet MS", 1, 12))); // NOI18N

        update_expenditureReasonIdComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_expenditureReasonIdComboBoxActionPerformed(evt);
            }
        });

        jLabel31.setText("Expenditure reason id :");

        jLabel32.setText("Expenditure reason :");

        update_expenditureReasonButton.setText("Update expenditure reason");
        update_expenditureReasonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_expenditureReasonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(update_expenditureReasonTextField)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(update_expenditureReasonIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 128, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(update_expenditureReasonButton)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_expenditureReasonIdComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(update_expenditureReasonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(update_expenditureReasonButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        expenditureReasonTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Expenditure id", "Expenditure reason"
            }
        ));
        jScrollPane3.setViewportView(expenditureReasonTable);

        javax.swing.GroupLayout manageResponsiblePanel1Layout = new javax.swing.GroupLayout(manageResponsiblePanel1);
        manageResponsiblePanel1.setLayout(manageResponsiblePanel1Layout);
        manageResponsiblePanel1Layout.setHorizontalGroup(
            manageResponsiblePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageResponsiblePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageResponsiblePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(manageResponsiblePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(820, Short.MAX_VALUE))
        );
        manageResponsiblePanel1Layout.setVerticalGroup(
            manageResponsiblePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(manageResponsiblePanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(manageResponsiblePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3)
                    .addGroup(manageResponsiblePanel1Layout.createSequentialGroup()
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        manageIncomeAndExpenditureReasonTabbedPane.addTab("Manage Expenditure Reason", manageResponsiblePanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manageIncomeAndExpenditureReasonTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(manageIncomeAndExpenditureReasonTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 255, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void save_incomeReasonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_incomeReasonButtonActionPerformed
        try {
            if (!add_incomeReasonText.getText().isEmpty()) {
                int result = incomeReasonController.addIncomeReason(add_incomeExpenditureIdLabel.getText(), add_incomeReasonText.getText());

                if (result == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Income reason saved successfully.");

                    add_incomeExpenditureIdLabel.setText(idGenerator.generateId("ir"));
                    add_incomeReasonText.setText(null);

                    loadComboForIncomeReason();
                    loadTableForIncomeReason();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Income reason saving failed. Please retry saving with corrrect details.");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "None of the fields cannot be null. Please recheck before you save income reason.");
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_save_incomeReasonButtonActionPerformed

    private void searchDelete_incomeReasonIdRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDelete_incomeReasonIdRadioButtonActionPerformed
        try {
            searchDelete_incomeReasonFirstLabel.setText("Income reason id :");
            searchDelete_incomeReasonSecondLabel.setText("Income reason :");

            loadComboForIncomeReason();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchDelete_incomeReasonIdRadioButtonActionPerformed

    private void searchDelete_incomeReasonRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDelete_incomeReasonRadioButtonActionPerformed
        try {
            searchDelete_incomeReasonFirstLabel.setText("Income reason :");
            searchDelete_incomeReasonSecondLabel.setText("Income reason id :");

            loadComboForIncomeReason();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchDelete_incomeReasonRadioButtonActionPerformed

    private void searchDelete_incomeReasonComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDelete_incomeReasonComboBoxActionPerformed
        try {
            switch (searchDelete_incomeReasonFirstLabel.getText()) {
                case "Income reason id :":
                    object = incomeReasonController.searchIncomeReason("incomeReason_id", searchDelete_incomeReasonComboBox.getSelectedItem() + "");
                    searchDelete_incomeReasonLabel.setText((String) object[1]);
                    break;
                case "Income reason :":
                    object = incomeReasonController.searchIncomeReason("incomeReason_title", searchDelete_incomeReasonComboBox.getSelectedItem() + "");
                    searchDelete_incomeReasonLabel.setText((String) object[0]);
                    break;
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchDelete_incomeReasonComboBoxActionPerformed

    private void delete_incomeReasonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_incomeReasonButtonActionPerformed
        try {
            int result = 0;
            switch (searchDelete_incomeReasonFirstLabel.getText()) {
                case "Income reason id :":
                    result = incomeReasonController.deleteIncomeReason(searchDelete_incomeReasonComboBox.getSelectedItem() + "");
                    break;
                case "Income reason :":
                    result = incomeReasonController.deleteIncomeReason(searchDelete_incomeReasonLabel.getText());
                    break;
            }

            if (result == 1) {
                JOptionPane.showMessageDialog(rootPane, "Income reason deleted successfully.");

                loadComboForIncomeReason();
                loadTableForIncomeReason();
                add_incomeExpenditureIdLabel.setText(idGenerator.generateId("ir"));
            } else {
                JOptionPane.showMessageDialog(rootPane, "Unable to delete the selected income reason.");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_delete_incomeReasonButtonActionPerformed

    private void update_incomeReasonIdComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_incomeReasonIdComboBoxActionPerformed
        try {
            object = incomeReasonController.searchIncomeReason("incomeReason_id", searchDelete_incomeReasonComboBox.getSelectedItem() + "");
            update_incomeReasonTextField.setText((String) object[1]);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_update_incomeReasonIdComboBoxActionPerformed

    private void update_incomeReasonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_incomeReasonButtonActionPerformed
        try {
            if (update_incomeReasonTextField.getText() != null) {
                int result = incomeReasonController.updateIncomeReason(update_incomeReasonIdComboBox.getSelectedItem() + "", update_incomeReasonTextField.getText());

                if (result == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Income reason updated successfully.");

                    loadComboForIncomeReason();
                    loadTableForIncomeReason();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Income reason failed to update.");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "None of the fields cannot be null. Please recheck before you update income reason.");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_update_incomeReasonButtonActionPerformed

    private void save_expenditureReasonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_expenditureReasonButtonActionPerformed
        try {
            if (!add_expenditureReasonText.getText().isEmpty()) {
                int result = expenditureReasonController.addExpenditureReason(add_expenditureIdLabel.getText(), add_expenditureReasonText.getText());

                if (result == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Expenditure reason saved successfully.");

                    add_expenditureIdLabel.setText(idGenerator.generateId("ir"));
                    add_expenditureReasonText.setText(null);

                    loadComboForExpenditureReason();
                    loadTableForExpenditureReason();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Expenditure reason saving failed. Please retry saving with corrrect details.");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "None of the fields cannot be null. Please recheck before you save expenditure reason.");
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_save_expenditureReasonButtonActionPerformed

    private void searchDelete_expenditureReasonIdRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDelete_expenditureReasonIdRadioButtonActionPerformed
        try {
            searchDelete_expenditureReasonFirstLabel.setText("Expenditure reason id :");
            searchDelete_expenditureReasonSecondLabel.setText("Expenditure reason :");

            loadComboForExpenditureReason();
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchDelete_expenditureReasonIdRadioButtonActionPerformed

    private void searchDelete_expenditureReasonRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDelete_expenditureReasonRadioButtonActionPerformed
        try {
            searchDelete_expenditureReasonFirstLabel.setText("Expenditure reason :");
            searchDelete_expenditureReasonSecondLabel.setText("Expenditure reason id :");

            loadComboForExpenditureReason();
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchDelete_expenditureReasonRadioButtonActionPerformed

    private void searchDelete_expenditureReasonComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchDelete_expenditureReasonComboBoxActionPerformed
        try {
            switch (searchDelete_expenditureReasonFirstLabel.getText()) {
                case "Expenditure reason id :":
                    object = expenditureReasonController.searchExpenditureReason("expenditureReason_id", searchDelete_expenditureReasonComboBox.getSelectedItem() + "");
                    searchDelete_expenditureReasonLabel.setText((String) object[1]);
                    break;
                case "Expenditure reason :":
                    object = expenditureReasonController.searchExpenditureReason("expenditureReason_title", searchDelete_expenditureReasonComboBox.getSelectedItem() + "");
                    searchDelete_expenditureReasonLabel.setText((String) object[0]);
                    break;
            }
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchDelete_expenditureReasonComboBoxActionPerformed

    private void delete_expenditureReasonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_expenditureReasonButtonActionPerformed
        try {
            int result = 0;
            switch (searchDelete_expenditureReasonFirstLabel.getText()) {
                case "Expenditure reason id :":
                    result = expenditureReasonController.deleteExpenditureReason(searchDelete_expenditureReasonComboBox.getSelectedItem() + "");
                    break;
                case "Expenditure reason :":
                    result = expenditureReasonController.deleteExpenditureReason(searchDelete_expenditureReasonLabel.getText());
                    break;
            }

            if (result == 1) {
                JOptionPane.showMessageDialog(rootPane, "Expenditure reason deleted successfully.");

                loadComboForExpenditureReason();
                loadTableForExpenditureReason();
                add_expenditureIdLabel.setText(idGenerator.generateId("er"));
            } else {
                JOptionPane.showMessageDialog(rootPane, "Unable to delete the selected income reason.");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_delete_expenditureReasonButtonActionPerformed

    private void update_expenditureReasonIdComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_expenditureReasonIdComboBoxActionPerformed
        try {
            object = expenditureReasonController.searchExpenditureReason("expenditureReason_id", searchDelete_expenditureReasonComboBox.getSelectedItem() + "");
            update_expenditureReasonTextField.setText((String) object[1]);
        } catch (SQLException | ClassNotFoundException ex) {
            Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_update_expenditureReasonIdComboBoxActionPerformed

    private void update_expenditureReasonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_expenditureReasonButtonActionPerformed
        try {
            if (update_expenditureReasonTextField.getText() != null) {
                int result = expenditureReasonController.updateExpenditureReason(update_expenditureReasonIdComboBox.getSelectedItem() + "", update_expenditureReasonTextField.getText());

                if (result == 1) {
                    JOptionPane.showMessageDialog(rootPane, "Expenditure reason updated successfully.");

                    loadComboForExpenditureReason();
                    loadTableForExpenditureReason();
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Expenditure reason failed to update.");
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "None of the fields cannot be null. Please recheck before you update expenditure reason.");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_update_expenditureReasonButtonActionPerformed

    private void loadComboForIncomeReason() throws ClassNotFoundException, SQLException {
        switch (searchDelete_incomeReasonFirstLabel.getText()) {
            case "Income reason id :":
                searchDelete_incomeReasonComboBox.removeAllItems();
                comboBoxFunctions.loadCombo(searchDelete_incomeReasonComboBox, "incomeReason", "incomeReason_id");
                comboSearch1.setSearchableCombo(searchDelete_incomeReasonComboBox, true, "No such income reason available");
                break;
            case "Income reason :":
                searchDelete_incomeReasonComboBox.removeAllItems();
                comboBoxFunctions.loadCombo(searchDelete_incomeReasonComboBox, "incomeReason", "incomeReason_title");
                comboSearch1.setSearchableCombo(searchDelete_incomeReasonComboBox, true, "No such income reason available");
                break;
        }

        update_incomeReasonIdComboBox.removeAllItems();
        comboBoxFunctions.loadCombo(update_incomeReasonIdComboBox, "incomeReason", "incomeReason_id");
        comboSearch2.setSearchableCombo(update_incomeReasonIdComboBox, true, "No such income reason available");
    }

    private void loadTableForIncomeReason() throws ClassNotFoundException, SQLException {
        dtmForIncomeReason.setRowCount(0);
        ArrayList<Object[]> arrayList = incomeReasonController.searchAllIncomeReason();

        for (int i = 0; i < arrayList.size(); i++) {
            dtmForIncomeReason.addRow(arrayList.get(i));
        }
    }

    private void loadComboForExpenditureReason() throws ClassNotFoundException, SQLException {
        switch (searchDelete_expenditureReasonFirstLabel.getText()) {
            case "Expenditure reason id :":
                searchDelete_expenditureReasonComboBox.removeAllItems();
                comboBoxFunctions.loadCombo(searchDelete_expenditureReasonComboBox, "expenditureReason", "expenditureReason_id");
                comboSearch3.setSearchableCombo(searchDelete_expenditureReasonComboBox, true, "No such expenditure reason available");
                break;
            case "Expenditure reason :":
                searchDelete_expenditureReasonComboBox.removeAllItems();
                comboBoxFunctions.loadCombo(searchDelete_expenditureReasonComboBox, "expenditureReason", "expenditureReason_title");
                comboSearch3.setSearchableCombo(searchDelete_expenditureReasonComboBox, true, "No such expenditure reason available");
                break;
        }

        update_expenditureReasonIdComboBox.removeAllItems();
        comboBoxFunctions.loadCombo(update_expenditureReasonIdComboBox, "expenditureReason", "expenditureReason_id");
        comboSearch4.setSearchableCombo(update_expenditureReasonIdComboBox, true, "No such expenditure reason available");
    }

    private void loadTableForExpenditureReason() throws ClassNotFoundException, SQLException {
        dtmForExpenditureReason.setRowCount(0);
        ArrayList<Object[]> arrayList = expenditureReasonController.searchAllExpenditureReason();

        for (int i = 0; i < arrayList.size(); i++) {
            dtmForExpenditureReason.addRow(arrayList.get(i));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageIncomeAndExpenditureReason.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageIncomeAndExpenditureReason().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel add_expenditureIdLabel;
    private javax.swing.JTextField add_expenditureReasonText;
    private javax.swing.JLabel add_incomeExpenditureIdLabel;
    private javax.swing.JTextField add_incomeReasonText;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton delete_expenditureReasonButton;
    private javax.swing.JButton delete_incomeReasonButton;
    private javax.swing.JTable expenditureReasonTable;
    private javax.swing.JTable incomeReasonTable;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTabbedPane manageIncomeAndExpenditureReasonTabbedPane;
    public javax.swing.JPanel manageResponsiblePanel;
    public javax.swing.JPanel manageResponsiblePanel1;
    private javax.swing.JButton save_expenditureReasonButton;
    private javax.swing.JButton save_incomeReasonButton;
    private javax.swing.JComboBox searchDelete_expenditureReasonComboBox;
    private javax.swing.JLabel searchDelete_expenditureReasonFirstLabel;
    private javax.swing.JRadioButton searchDelete_expenditureReasonIdRadioButton;
    private javax.swing.JLabel searchDelete_expenditureReasonLabel;
    private javax.swing.JRadioButton searchDelete_expenditureReasonRadioButton;
    private javax.swing.JLabel searchDelete_expenditureReasonSecondLabel;
    private javax.swing.JComboBox searchDelete_incomeReasonComboBox;
    private javax.swing.JLabel searchDelete_incomeReasonFirstLabel;
    private javax.swing.JRadioButton searchDelete_incomeReasonIdRadioButton;
    private javax.swing.JLabel searchDelete_incomeReasonLabel;
    private javax.swing.JRadioButton searchDelete_incomeReasonRadioButton;
    private javax.swing.JLabel searchDelete_incomeReasonSecondLabel;
    private javax.swing.JButton update_expenditureReasonButton;
    private javax.swing.JComboBox update_expenditureReasonIdComboBox;
    private javax.swing.JTextField update_expenditureReasonTextField;
    private javax.swing.JButton update_incomeReasonButton;
    private javax.swing.JComboBox update_incomeReasonIdComboBox;
    private javax.swing.JTextField update_incomeReasonTextField;
    // End of variables declaration//GEN-END:variables
}
